---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    app: cms
    author: Rohith
spec:
  containers:
    - name: ghost
      image: ghost
      env:
        - name: NODE_ENV
          value: development
...