---
apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels:
    app: webserver
    author: Rohith
spec:
  replicas: 2
  template:
    metadata:
      name: httpd-pod
      labels:
        app: webserver
        author: Rohith
    spec:
      containers:
        - name: myhttpd
          image: httpd
          ports:
            - containerPort: 80
              hostPort: 8080
...