---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    author: Rohith
spec:
  type: ClusterIP
  selector:
    type: db
  ports:
    - targetPort: 5432
      port: 5432
...