---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  labels:
    author: Rohith
spec:
  type: NodePort
  selector:
    type: proxy
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
...