---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    author: Rohith
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - targetPort: 3306
      port: 3306
  ...